Medical Inventory/Controllers/AuthController.cs
using Entities;
using Inventory.DAL;
using Medical_Inventory.Models.ViewModel.AuthViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Medical_Inventory.Controllers;

    public class AuthController : Controller
    {
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly RoleManager<ApplicationRole> _roleManager;
    private readonly SignInManager<ApplicationUser> _signInManager;

    public AuthController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<ApplicationRole> roleManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _roleManager = roleManager;
    }

    [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterVm model)
        {
            if (!ModelState.IsValid) return View(model);

            var user = await _userManager.FindByNameAsync(model.UserName);

            if (user is not null)
            {
                TempData["Error"] = "User name already exists";
                return View(model);
            }

            var newUser = new ApplicationUser()
            {
                UserName = model.UserName
            };
            var response = await _userManager.CreateAsync(newUser, model.Password);

            if (!response.Succeeded)
            {
                TempData["Error"] = "User registration failed";
                return View(model);
            }
            await _userManager.AddToRoleAsync(newUser, StaticData.RoleUser);

            var result = await _signInManager.PasswordSignInAsync(newUser, model.Password, false, false);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Index), "Home");
            }

            TempData["Error"] = "Something wrong, trying again later";
            return View(model);
        }



    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginVm model)
    {
        if (!ModelState.IsValid) return View(model);

        var user = await _userManager.FindByNameAsync(model.UserName);

        if (user is not null)
        {
            var checkCredentials = await _userManager.CheckPasswordAsync(user, model.Password);
            if (checkCredentials)
            {
                var result = await _signInManager.PasswordSignInAsync(user, model.Password, false, false);
                if (result.Succeeded)
                    return RedirectToAction(nameof(Index), "Home");
            }
        }

        TempData["Error"] = "wrong credentials, please try again";
        return View(model);
    }

    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction(nameof(Index), "Home");
    }

    public IActionResult AccessDenied()
    {
        return View();
    }


}

Medical Inventory/Controllers/CompaniesController.cs
using System.Security.Claims;
using Entities;
using Inventory.DAL;
using Inventory.Service.IRepository;
using Inventory.Utility.Exceptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Medical_Inventory.Controllers;

[Authorize(Roles = StaticData.RoleAdmin)]
public class CompaniesController : Controller
{
    private readonly ILogger<CompaniesController> _logger;
    private readonly ICompanyRepository _companyRepository;

    public CompaniesController(ILogger<CompaniesController> logger, ICompanyRepository companyRepository)
    {
        _logger = logger;
        _companyRepository = companyRepository;
    }


    // GET: Companies
    public async Task<IActionResult> Index()
    {
        try
        {
            var result = await _companyRepository.GetAll()!;
            return View(result);
        }
        catch (Exception)
        {
            _logger.LogError("failed to load categories");
        }

        return View(null);
    }

    // GET: Companies/Details/5
    public async Task<IActionResult> Details(long? id)
    {
        try
        {
            var result = await _companyRepository.GetFirstOrDefault(id)!;
            return View(result);
        }
        catch (NotFoundException ex)
        {
            _logger.LogWarning(ex.Message);
            return RedirectToAction("PageNotFound", "Home");
        }
        catch (Exception)
        {
            throw;
        }
        
    }

    // GET: Companies/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Companies/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Phone,Address")] Company company)
    {
        try
        {
            var existsCompany = await _companyRepository.GetByName(company.Name)!;

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
            company.CreatedTime = DateTime.Now;
            company.UpdatedTime = DateTime.Now;
            company.CreatedById = long.Parse(userId);
            company.UpdatedById = long.Parse(userId);

            await _companyRepository.Add(company);

            _logger.LogInformation(message: $"new company added with name of {company.Name}");
            return RedirectToAction(nameof(Index));
        }
        catch (DuplicationException ex)
        {
            ModelState.AddModelError(string.Empty, company.Name + " already exists");
            _logger.LogWarning(ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex.Message);
            throw;
        }

        if (!ModelState.IsValid) return View(company);

        return RedirectToAction(nameof(Index));
    }

    // GET: Companies/Edit/5
    public async Task<IActionResult> Edit(long? id)
    {
        try
        {
            var company = await _companyRepository.GetFirstOrDefault(id)!;

            return View(company);
        }
        catch (NotFoundException ex)
        {
            _logger.LogWarning($"category not found of id: {id}");
            return RedirectToAction("PageNotFound", "Home");
        }
        catch (Exception)
        {

            throw;
        }

    }

    // POST: Companies/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(long id, [Bind("Id,Name,Phone,Address")] Company company)
    {
        try
        {
            var existsCompany = await _companyRepository.GetByName(company.Name, id)!;

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
            company.UpdatedById = long.Parse(userId);

            _companyRepository.Update(company);
            await _companyRepository.Save();

            _logger.LogWarning($"category updated of id: {id}");

            return RedirectToAction(nameof(Index));
        }
        catch (NotFoundException)
        {
            _logger.LogWarning($"company not found of id: {id}");
            return NotFound();
        }
        catch (DuplicationException ex)
        {
            _logger.LogWarning($"company alaready exists of name: {company.Name}");
            ModelState.AddModelError(string.Empty, company.Name + " already exists");
        }
        catch (Exception ex)
        {
            _logger.LogWarning($"Failed to update data of id: {id}");
            _logger.LogWarning(ex.Message);
        }

        return View(company);
    }

    // GET: Companies/Delete/5
    public async Task<IActionResult> Delete(long? id)
    {
        try
        {
            var company = await _companyRepository.GetFirstOrDefault(id)!;
            if (company != null)
            {
                return View(company);
            }
        }
        catch (Exception)
        {
            _logger.LogError($"something wrong to find company with id: {id}");
        }
        
        return RedirectToAction("PageNotFound", "Home");
    }

    // POST: Companies/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(long id)
    {
        try
        {
            var company = await _companyRepository.GetFirstOrDefault(id)!;
            if (company != null)
            {
                await _companyRepository.Remove(company);
            }
        }
        catch (Exception)
        {
            _logger.LogError($"something wrong to find company with id: {id}");
        }        
            
        return RedirectToAction(nameof(Index));
    }
        
}

Medical Inventory/Controllers/GenericsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
using System.Security.Claims;
using Entities;
using Inventory.Service.IRepository;
using Inventory.Utility.Exceptions;

namespace Medical_Inventory.Controllers;

[Authorize]
public class GenericsController : Controller
{
    private readonly ILogger<CompaniesController> _logger;
    private readonly IGenericRepository _genericRepository;

    public GenericsController(ILogger<CompaniesController> logger, IGenericRepository genericRepository)
    {
        _logger = logger;
        _genericRepository = genericRepository;
    }

    // GET: Generics
    public async Task<IActionResult> Index()
    {
        try
        {
            var result = await _genericRepository.GetAll()!;

            return View(result);
        }
        catch (Exception)
        {
            _logger.LogError("failed to load generics");
        }

        return View(null);
    }

    // GET: Generics/Details/5
    public async Task<IActionResult> Details(long? id)
    {
        try
        {
            var result = await _genericRepository.GetFirstOrDefault(id)!;
            return View(result);
        }
        catch (NotFoundException ex)
        {
            _logger.LogWarning(ex.Message);
            return RedirectToAction("PageNotFound", "Home");
        }
        catch (Exception)
        {
            throw;
        }

    }

    // GET: Generics/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Generics/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name")] Generic generic)
    {
        try
        {
            var existsGeneric = await _genericRepository.GetByName(generic.Name)!;

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
            generic.CreatedTime = DateTime.Now;
            generic.UpdatedTime = DateTime.Now;
            generic.CreatedById = long.Parse(userId);
            generic.UpdatedById = long.Parse(userId);

            await _genericRepository.Add(generic);
            await _genericRepository.Save();

            _logger.LogInformation(message: $"new generic added with name of {generic.Name}");
            return RedirectToAction(nameof(Index));
        }
        catch (DuplicationException ex)
        {
            ModelState.AddModelError(string.Empty, generic.Name + " already exists");
            _logger.LogWarning(ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex.Message);
            throw;
        }

        if (!ModelState.IsValid) return View(generic);

        return RedirectToAction(nameof(Index));
    }

    // GET: Generics/Edit/5
    public async Task<IActionResult> Edit(long? id)
    {
        try
        {
            var generic = await _genericRepository.GetFirstOrDefault(id)!;

            return View(generic);
        }
        catch (NotFoundException ex)
        {
            _logger.LogWarning($"generic not found of id: {id}");
            return RedirectToAction("PageNotFound", "Home");
        }
        catch (Exception)
        {
            throw;
        }
    }

    // POST: Generics/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(long id, [Bind("Id,Name")] Generic generic)
    {
        try
        {
            var existsCompany = await _genericRepository.GetByName(generic.Name, id)!;

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
            generic.UpdatedById = long.Parse(userId);

            _genericRepository.Update(generic);
            await _genericRepository.Save();

            _logger.LogWarning($"generic updated of id: {id}");

            return RedirectToAction(nameof(Index));
        }
        catch (NotFoundException)
        {
            _logger.LogWarning($"generic not found of id: {id}");
            return NotFound();
        }
        catch (DuplicationException ex)
        {
            _logger.LogWarning($"generic alaready exists of name: {generic.Name}");
            ModelState.AddModelError(string.Empty, generic.Name + " already exists");
        }
        catch (Exception ex)
        {
            _logger.LogError($"Failed to update generic of id: {id}");
            _logger.LogWarning(ex.Message);
        }

        return View(generic);
    }

    // GET: Generics/Delete/5
    public async Task<IActionResult> Delete(long? id)
    {
        var generic = await _genericRepository.GetFirstOrDefault(id)!;
        if (generic == null)
        {
            return NotFound();
        }

        return View(generic);
    }

    // POST: Generics/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(long id)
    {
        try
        {
            var generic = await _genericRepository.GetFirstOrDefault(id)!;
            if (generic != null)
            {
                await _genericRepository.Remove(generic);
            }
        }
        catch(Exception ex)
        {
            _logger.LogError($"failed to delete generic of id: {id}");
            _logger.LogError(ex.Message);
        }
        
        return RedirectToAction(nameof(Index));
    }
}

Medical Inventory/Views/Shared/_Identity.cshtml
<ul class="navbar nav me-5">
    @if (!User.Identity.IsAuthenticated)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
        </li>
    }
    else
    {
        <li class="nav-item me-2">@User.Identity.Name</li>
        <li class="nav-item">
            @* <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Log out</a> *@
            <form asp-controller="Auth" asp-action="Logout" method="post">
                <button class="btn btn-outline-danger">Log out</button>
            </form>
        </li>
    }

</ul>

Medical Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Medical_Inventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Medical_Inventory.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Medical Inventory</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="PatientGroups" asp-action="Index">Patient Group</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Generics" asp-action="Index">Generic</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Company</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                    </li>


                </ul>

                <partial name="_Identity"/>


            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year - Medical Inventory
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>